sudo: true
language: python
cache:
  pip: true
python:
  - "3.4.3"
before_script:
  - psql -c 'create database travisci;' -U postgres
install:
  - pip install -r requirements/test.txt
script: "python manage.py test"
